// <auto-generated />
using System;
using FindFun.Server.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FindFun.Server.Migrations
{
    [DbContext(typeof(FindFunDbContext))]
    [Migration("20260323134159_AddReviews")]
    partial class AddReviews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FindFun.Server.Domain.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Point>("Coordinates")
                        .HasColumnType("geometry")
                        .HasColumnName("coordinates");

                    b.Property<string>("Line")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("line1");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<int>("StreetId")
                        .HasColumnType("integer")
                        .HasColumnName("street_id");

                    b.HasKey("Id");

                    b.HasIndex("StreetId");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("FindFun.Server.Domain.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("amenities", (string)null);
                });

            modelBuilder.Entity("FindFun.Server.Domain.ClosingSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ParkId")
                        .HasColumnType("integer")
                        .HasColumnName("park_id");

                    b.HasKey("Id");

                    b.HasIndex("ParkId")
                        .IsUnique();

                    b.ToTable("closing_schedules", (string)null);
                });

            modelBuilder.Entity("FindFun.Server.Domain.Municipality", b =>
                {
                    b.Property<int>("Gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("gid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Gid"));

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon,4326)")
                        .HasColumnName("geom");

                    b.Property<string>("Iso31663")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("iso_3166_3");

                    b.Property<string>("LocalName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("local_name_");

                    b.Property<string>("OfficialCo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("official_co");

                    b.Property<string>("OfficialCo3")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("official_co__3");

                    b.Property<string>("OfficialCo5")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("official_co__5");

                    b.Property<string>("OfficialNa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("official_na");

                    b.Property<string>("OfficialNa4")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("official_na_4");

                    b.Property<string>("OfficialNa6")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("official_na__6");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("type");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("year");

                    b.HasKey("Gid");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "GIST");

                    b.HasIndex("OfficialNa6");

                    b.ToTable("georef-spain-municipio-millesime", "public");
                });

            modelBuilder.Entity("FindFun.Server.Domain.Park", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer")
                        .HasColumnName("address_id");

                    b.Property<string>("AgeRecommendation")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("all")
                        .HasColumnName("age_recommendation");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("EntranceFee")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("entrance_fee");

                    b.Property<bool>("IsFree")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_free");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Organizer")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("organizer");

                    b.Property<string>("ParkType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("park_type");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("parks", (string)null);
                });

            modelBuilder.Entity("FindFun.Server.Domain.ParkAmenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AmenityId")
                        .HasColumnType("integer")
                        .HasColumnName("amenity_id");

                    b.Property<int>("ParkId")
                        .HasColumnType("integer")
                        .HasColumnName("park_id");

                    b.HasKey("Id");

                    b.HasIndex("AmenityId");

                    b.HasIndex("ParkId");

                    b.ToTable("park_amenities", (string)null);
                });

            modelBuilder.Entity("FindFun.Server.Domain.ParkImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ParkId")
                        .HasColumnType("integer")
                        .HasColumnName("park_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ParkId");

                    b.ToTable("park_images", (string)null);
                });

            modelBuilder.Entity("FindFun.Server.Domain.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid");

                    b.Property<int>("ParkId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParkId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("FindFun.Server.Domain.Street", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MunicipioGid")
                        .HasColumnType("integer")
                        .HasColumnName("municipio_gid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MunicipioGid");

                    b.HasIndex("Name", "MunicipioGid")
                        .IsUnique();

                    b.ToTable("streets", (string)null);
                });

            modelBuilder.Entity("FindFun.Server.Domain.Address", b =>
                {
                    b.HasOne("FindFun.Server.Domain.Street", "Street")
                        .WithMany("Addresses")
                        .HasForeignKey("StreetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Street");
                });

            modelBuilder.Entity("FindFun.Server.Domain.ClosingSchedule", b =>
                {
                    b.HasOne("FindFun.Server.Domain.Park", "Park")
                        .WithOne("ClosingSchedule")
                        .HasForeignKey("FindFun.Server.Domain.ClosingSchedule", "ParkId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.OwnsMany("FindFun.Server.Domain.ClosingScheduleEntry", "Entries", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<string>("ClosesAt")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("closes_at");

                            b1.Property<string>("Day")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("day");

                            b1.Property<bool>("IsClosed")
                                .HasColumnType("boolean")
                                .HasColumnName("is_closed");

                            b1.Property<string>("OpensAt")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("opens_at");

                            b1.Property<int>("closing_schedule_id")
                                .HasColumnType("integer");

                            b1.HasKey("id");

                            b1.HasIndex("closing_schedule_id");

                            b1.ToTable("closing_schedule_entries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("closing_schedule_id");
                        });

                    b.Navigation("Entries");

                    b.Navigation("Park");
                });

            modelBuilder.Entity("FindFun.Server.Domain.Park", b =>
                {
                    b.HasOne("FindFun.Server.Domain.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("FindFun.Server.Domain.ParkAmenity", b =>
                {
                    b.HasOne("FindFun.Server.Domain.Amenity", "Amenity")
                        .WithMany("ParkAmenities")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FindFun.Server.Domain.Park", "Park")
                        .WithMany("Amenities")
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Park");
                });

            modelBuilder.Entity("FindFun.Server.Domain.ParkImage", b =>
                {
                    b.HasOne("FindFun.Server.Domain.Park", "Park")
                        .WithMany("Images")
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Park");
                });

            modelBuilder.Entity("FindFun.Server.Domain.Review", b =>
                {
                    b.HasOne("FindFun.Server.Domain.Park", "Park")
                        .WithMany("Reviews")
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Park");
                });

            modelBuilder.Entity("FindFun.Server.Domain.Street", b =>
                {
                    b.HasOne("FindFun.Server.Domain.Municipality", "Municipio")
                        .WithMany("Streets")
                        .HasForeignKey("MunicipioGid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("FindFun.Server.Domain.Amenity", b =>
                {
                    b.Navigation("ParkAmenities");
                });

            modelBuilder.Entity("FindFun.Server.Domain.Municipality", b =>
                {
                    b.Navigation("Streets");
                });

            modelBuilder.Entity("FindFun.Server.Domain.Park", b =>
                {
                    b.Navigation("Amenities");

                    b.Navigation("ClosingSchedule");

                    b.Navigation("Images");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("FindFun.Server.Domain.Street", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
