// <auto-generated />
using System;
using System.Resources;
using System.Globalization;

namespace FindFun.Server.Shared.Resources
{
    internal static class Messages
    {
        private static ResourceManager? resourceManager;

        internal static ResourceManager ResourceManager => resourceManager ??= new ResourceManager("FindFun.Server.Shared.Resources.Messages", typeof(Messages).Assembly);

        internal static string InvalidCoordinateFormat => ResourceManager.GetString("InvalidCoordinateFormat", CultureInfo.CurrentUICulture) ?? string.Empty;
        internal static string AmenitiesCannotBeEmpty => ResourceManager.GetString("AmenitiesCannotBeEmpty", CultureInfo.CurrentUICulture) ?? string.Empty;
        internal static string EntranceFeeMustBeZeroWhenFree => ResourceManager.GetString("EntranceFeeMustBeZeroWhenFree", CultureInfo.CurrentUICulture) ?? string.Empty;
        internal static string EntranceFeeGreaterThanZero => ResourceManager.GetString("EntranceFeeGreaterThanZero", CultureInfo.CurrentUICulture) ?? string.Empty;
        internal static string ValidationErrorsOccurred => ResourceManager.GetString("ValidationErrorsOccurred", CultureInfo.CurrentUICulture) ?? string.Empty;
        internal static string ParkNotFound => ResourceManager.GetString("ParkNotFound", CultureInfo.CurrentUICulture) ?? string.Empty;
        internal static string LocalityNotFound => ResourceManager.GetString("LocalityNotFound", CultureInfo.CurrentUICulture) ?? string.Empty;
        internal static string AddressAlreadyExists => ResourceManager.GetString("AddressAlreadyExists", CultureInfo.CurrentUICulture) ?? string.Empty;
        internal static string OneOrMoreImagesFailedToUpload => ResourceManager.GetString("OneOrMoreImagesFailedToUpload", CultureInfo.CurrentUICulture) ?? string.Empty;
        internal static string FailedToCreatePark => ResourceManager.GetString("FailedToCreatePark", CultureInfo.CurrentUICulture) ?? string.Empty;
        internal static string ConnectionStringBlobsNotFound => ResourceManager.GetString("ConnectionStringBlobsNotFound", CultureInfo.CurrentUICulture) ?? string.Empty;
        internal static string UnhandledExceptionOccurred => ResourceManager.GetString("UnhandledExceptionOccurred", CultureInfo.CurrentUICulture) ?? string.Empty;
        internal static string FieldCoordinates => ResourceManager.GetString("FieldCoordinates", CultureInfo.CurrentUICulture) ?? string.Empty;
        internal static string FieldAmenities => ResourceManager.GetString("FieldAmenities", CultureInfo.CurrentUICulture) ?? string.Empty;
        internal static string FieldEntranceFee => ResourceManager.GetString("FieldEntranceFee", CultureInfo.CurrentUICulture) ?? string.Empty;
        internal static string FieldLocality => ResourceManager.GetString("FieldLocality", CultureInfo.CurrentUICulture) ?? string.Empty;
        internal static string FieldAddress => ResourceManager.GetString("FieldAddress", CultureInfo.CurrentUICulture) ?? string.Empty;
        internal static string FieldParkImages => ResourceManager.GetString("FieldParkImages", CultureInfo.CurrentUICulture) ?? string.Empty;
        internal static string FieldPark => ResourceManager.GetString("FieldPark", CultureInfo.CurrentUICulture) ?? string.Empty;
        internal static string FieldParkId => ResourceManager.GetString("FieldParkId", CultureInfo.CurrentUICulture) ?? string.Empty;
    }
}

