// <auto-generated />
using System;
using System.Resources;
using System.Globalization;

namespace FindFun.Server.Shared.File.Resources
{
    internal static class Messages
    {
        private static ResourceManager? resourceManager;

        internal static ResourceManager ResourceManager => resourceManager ??= new ResourceManager("FindFun.Server.Shared.File.Resources.Messages", typeof(Messages).Assembly);

        internal static string NoFilesProvided => ResourceManager.GetString("NoFilesProvided", CultureInfo.CurrentUICulture) ?? string.Empty;

        internal static string FileSizeInvalid => ResourceManager.GetString("FileSizeInvalid", CultureInfo.CurrentUICulture) ?? string.Empty;

        internal static string InvalidFileExtension => ResourceManager.GetString("InvalidFileExtension", CultureInfo.CurrentUICulture) ?? string.Empty;
    }
}
