/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export { }

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents
  {
    AccessibleInput: typeof import('./components/AccessibleInput.vue')['default']
    ActionsCard: typeof import('./components/ActionsCard.vue')['default']
    AmenitiesSelector: typeof import('./components/AmenitiesSelector.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('./components/Card.vue')['default']
    Carousel: typeof import('primevue/carousel')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ChipsCard: typeof import('./components/ChipsCard.vue')['default']
    ClosingSchedule: typeof import('./components/ClosingSchedule.vue')['default']
    ColorMode: typeof import('./components/ColorMode.vue')['default']
    ContentGrid: typeof import('./components/ContentGrid.vue')['default']
    DataView: typeof import('primevue/dataview')['default']
    DesktopNavigationBar: typeof import('./components/DesktopNavigationBar.vue')['default']
    Details: typeof import('./components/Details.vue')['default']
    DynamicFields: typeof import('./components/DynamicFields.vue')['default']
    EventParkDetails: typeof import('./components/EventParkDetails.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Galleria: typeof import('primevue/galleria')['default']
    GoogleMap: typeof import('./components/GoogleMap.vue')['default']
    // ...existing code...
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    ImageCard: typeof import('./components/ImageCard.vue')['default']
    InfoCard: typeof import('./components/InfoCard.vue')['default']
    // ...existing code...
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    MainCarousel: typeof import('./components/MainCarousel.vue')['default']
    MapLoader: typeof import('./components/MapLoader.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    MobileNavigationBar: typeof import('./components/MobileNavigationBar.vue')['default']
    NavBarUserSection: typeof import('./components/NavBarUserSection.vue')['default']
    ParkEventTab: typeof import('./components/ParkEventTab.vue')['default']
    ParkInfoPanel: typeof import('./components/ParkInfoPanel.vue')['default']
    Rating: typeof import('primevue/rating')['default']
    RelatedList: typeof import('./components/RelatedList.vue')['default']
    // ...existing code...
    ReviewForm: typeof import('./components/ReviewForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollTop: typeof import('primevue/scrolltop')['default']
    SectionHeader: typeof import('./components/SectionHeader.vue')['default']
    SignupForm: typeof import('./components/SignupForm.vue')['default']
    StatusTag: typeof import('./components/StatusTag.vue')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabView: typeof import('primevue/tabview')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    // ...existing code...
    UserRateing: typeof import('./components/UserRateing.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
  export interface GlobalDirectives
  {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
